apply plugin: 'com.android.application'

android {
    namespace "ir.caspiansoftware.caspianandroidapp"
    compileSdk = 37
    defaultConfig {
        applicationId "ir.caspiansoftware.caspianandroidapp"
        minSdk = 29
        targetSdk = 37
        versionCode 2
        versionName '2.4.7'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}



dependencies {

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test:rules:1.7.0'

    implementation 'androidx.core:core-ktx:1.19.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation project(':elyasilib')

    // https://mvnrepository.com/artifact/commons-net/commons-net
    implementation "commons-net:commons-net:3.13.0"

    // Lombok dependency
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    // https://mvnrepository.com/artifact/com.itextpdf.android/itext-core-android
    /*implementation 'com.itextpdf.android:itext-core-android:8.0.5'
    // https://mvnrepository.com/artifact/com.itextpdf.android/layout-android
    implementation 'com.itextpdf.android:layout-android:8.0.5'
    // https://mvnrepository.com/artifact/com.itextpdf.android/kernel-android
    implementation 'com.itextpdf.android:kernel-android:8.0.5'
    implementation 'com.itextpdf:typography:4.0.2'*/

    // https://mvnrepository.com/artifact/org.apache.pdfbox/pdfbox
    //implementation 'org.apache.pdfbox:pdfbox:2.0.33'

    // https://mvnrepository.com/artifact/com.ibm.icu/icu4j
    //implementation 'com.ibm.icu:icu4j:76.1'


    //implementation files('./typography-4.0.2.jar')
    //
    //implementation 'com.ibm.icu:icu4j:71.1'



}